default_install_hook_types: [pre-commit]
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ['--dev', '-f', 'requirements.txt', '-o', 'requirements.txt']
  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: ./node_modules/.bin/stylelint
        language: node
        files: ^scss/
        types: [scss]
        args: ['--fix']
